Tracker:AddLocations("locations/Abandoned Barrack.json")
Tracker:AddLocations("locations/Altar of Hands.json")
Tracker:AddLocations("locations/Arctic Eden.json")
Tracker:AddLocations("locations/Aurum Mine.json")
Tracker:AddLocations("locations/Avian Gaol.json")
Tracker:AddLocations("locations/Baby Storage.json")
Tracker:AddLocations("locations/Bhaile Ruins.json")
Tracker:AddLocations("locations/Blazing Bonanza.json")
Tracker:AddLocations("locations/Blessed Optica.json")
Tracker:AddLocations("locations/Chronia Cyclone.json")
Tracker:AddLocations("locations/DKs Curse.json")
Tracker:AddLocations("locations/Dissolving Tower.json")
Tracker:AddLocations("locations/Drained Urbs.json")
Tracker:AddLocations("locations/Dunkelwald.json")
Tracker:AddLocations("locations/Flooded Manachainn.json")
Tracker:AddLocations("locations/Frost Burg.json")
Tracker:AddLocations("locations/Frostown Ruins.json")
Tracker:AddLocations("locations/Frosty Bait.json")
Tracker:AddLocations("locations/Frozen Gears.json")
Tracker:AddLocations("locations/Fungal Depths.json")
Tracker:AddLocations("locations/Gearserker Junction.json")
Tracker:AddLocations("locations/Giants Fire.json")
Tracker:AddLocations("locations/Golden Inneal.json")
Tracker:AddLocations("locations/Gravity Well.json")
Tracker:AddLocations("locations/Heavenly Aqueducts.json")
Tracker:AddLocations("locations/Industrial nest.json")
Tracker:AddLocations("locations/Jester.json")
Tracker:AddLocations("locations/Jesters Juicery.json")
Tracker:AddLocations("locations/Jesters Leviathan.json")
Tracker:AddLocations("locations/Jesters Minery.json")
Tracker:AddLocations("locations/Kappernian Springs.json")
Tracker:AddLocations("locations/Laser Marathon.json")
Tracker:AddLocations("locations/Lofty Highways.json")
Tracker:AddLocations("locations/Logtown.json")
Tracker:AddLocations("locations/Lonely Glacier.json")
Tracker:AddLocations("locations/Merchants Fleet.json")
Tracker:AddLocations("locations/Night Sight.json")
Tracker:AddLocations("locations/Optica Festival.json")
Tracker:AddLocations("locations/Radio Towers.json")
Tracker:AddLocations("locations/Ragnar.json")
Tracker:AddLocations("locations/Red Forest.json")
Tracker:AddLocations("locations/Roc.json")
Tracker:AddLocations("locations/Rotund Ice.json")
Tracker:AddLocations("locations/Runas Village.json")
Tracker:AddLocations("locations/Sgudal Ruins.json")
Tracker:AddLocations("locations/Shipwreck Twins.json")
Tracker:AddLocations("locations/Shroomfall.json")
Tracker:AddLocations("locations/Skull Sceal.json")
Tracker:AddLocations("locations/Slippery Slope.json")
Tracker:AddLocations("locations/Slocfall.json")
Tracker:AddLocations("locations/Smugglers Den.json")
Tracker:AddLocations("locations/Snowstorm Station.json")
Tracker:AddLocations("locations/Split Islands.json")
Tracker:AddLocations("locations/Stacked Outpost.json")
Tracker:AddLocations("locations/Stiltsville Ruins.json")
Tracker:AddLocations("locations/Subway Ascension.json")
Tracker:AddLocations("locations/Sunken Neighborhood.json")
Tracker:AddLocations("locations/Tartar Village.json")
Tracker:AddLocations("locations/The Crooked Crow.json")
Tracker:AddLocations("locations/Trading Outpost.json")
Tracker:AddLocations("locations/Tridentarius.json")
Tracker:AddLocations("locations/Tridentarius Gearserkium.json")
Tracker:AddLocations("locations/Twisting Barrels.json")
Tracker:AddLocations("locations/Uisge Whirlpool.json")
Tracker:AddLocations("locations/Vindras Mills.json")
Tracker:AddLocations("locations/Overworld.json")
